---
title: "E15_Oct10_scrubletOutput"
output: html_document
---

```{r}
barcode_mut_green<-read.csv(file="/home/ubuntu/velocyto/E15_Oct_mm10.1.2.0/E15_Oct10_mut_green/filtered_feature_bc_matrix/barcodes.tsv",header=F,sep="\t",stringsAsFactors = F)
barcode_mut_green<-unlist(barcode_mut_green,use.names = F)
barcode_mut_green<-gsub("-1","",barcode_mut_green)
barcode_mut_green<-paste("E15_Oct10_mut_green_",barcode_mut_green,sep="")
doublet_score_mut_green<-read.csv(file="/home/ubuntu/scrublet/examples/E15_Oct10_mut_green_doubletScore.csv",header=F,sep=",",stringsAsFactors = F)
doublet_score_mut_green<-unlist(doublet_score_mut_green,use.names = F)
names(doublet_score_mut_green)<-barcode_mut_green
```
```{r}
head(doublet_score_mut_green)

```
Do the same thing for all the channels, and put them together:
```{r}
barcode_mut_red<-read.csv(file="/home/ubuntu/velocyto/E15_Oct_mm10.1.2.0/E15_Oct10_mut_red/filtered_feature_bc_matrix/barcodes.tsv",header=F,sep="\t",stringsAsFactors = F)
barcode_mut_red<-unlist(barcode_mut_red,use.names = F)
barcode_mut_red<-gsub("-1","",barcode_mut_red)
barcode_mut_red<-paste("E15_Oct10_mut_red_",barcode_mut_red,sep="")
doublet_score_mut_red<-read.csv(file="/home/ubuntu/scrublet/examples/E15_Oct10_mut_red_doubletScore.csv",header=F,sep=",",stringsAsFactors = F)
doublet_score_mut_red<-unlist(doublet_score_mut_red,use.names = F)
names(doublet_score_mut_red)<-barcode_mut_red
```
```{r}
head(doublet_score_mut_red)

```

```{r}
barcode_wt_green<-read.csv(file="/home/ubuntu/velocyto/E15_Oct_mm10.1.2.0/E15_Oct10_wt_green/filtered_feature_bc_matrix/barcodes.tsv",header=F,sep="\t",stringsAsFactors = F)
barcode_wt_green<-unlist(barcode_wt_green,use.names = F)
barcode_wt_green<-gsub("-1","",barcode_wt_green)
barcode_wt_green<-paste("E15_Oct10_wt_green_",barcode_wt_green,sep="")
doublet_score_wt_green<-read.csv(file="/home/ubuntu/scrublet/examples/E15_Oct10_wt_green_doubletScore.csv",header=F,sep=",",stringsAsFactors = F)
doublet_score_wt_green<-unlist(doublet_score_wt_green,use.names = F)
names(doublet_score_wt_green)<-barcode_wt_green
```
```{r}
head(doublet_score_wt_green)

```
```{r}
barcode_wt_red<-read.csv(file="/home/ubuntu/velocyto/E15_Oct_mm10.1.2.0/E15_Oct10_wt_red/filtered_feature_bc_matrix/barcodes.tsv",header=F,sep="\t",stringsAsFactors = F)
barcode_wt_red<-unlist(barcode_wt_red,use.names = F)
barcode_wt_red<-gsub("-1","",barcode_wt_red)
barcode_wt_red<-paste("E15_Oct10_wt_red_",barcode_wt_red,sep="")
doublet_score_wt_red<-read.csv(file="/home/ubuntu/scrublet/examples/E15_Oct10_wt_red_doubletScore.csv",header=F,sep=",",stringsAsFactors = F)
doublet_score_wt_red<-unlist(doublet_score_wt_red,use.names = F)
names(doublet_score_wt_red)<-barcode_wt_red
```
```{r}
head(doublet_score_wt_red)

```


```{r}
E15_Oct10_doubletScore<-c(doublet_score_wt_green,doublet_score_wt_red,doublet_score_mut_green,doublet_score_mut_red)
```
```{r}
save(E15_Oct10_doubletScore,file="E15_Oct10_doubletScore.RData")
```
